"""Create weekly_rate_locks table

Revision ID: 070a5bfdf95b
Revises: b5a7075b8d11
Create Date: 2025-10-17 15:26:58.776065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070a5bfdf95b'
down_revision: Union[str, Sequence[str], None] = 'b5a7075b8d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
