"""Add logistics fields to purchase orders

Revision ID: 3156dcf00f26
Revises: d2c2c055b2df
Create Date: 2025-10-16 14:32:57.356688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3156dcf00f26'
down_revision: Union[str, Sequence[str], None] = 'd2c2c055b2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('assigned_driver', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('pickup_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'pickup_time')
    op.drop_column('purchase_orders', 'assigned_driver')
    # ### end Alembic commands ###
