"""Add temperature field to PO

Revision ID: b5a7075b8d11
Revises: 3156dcf00f26
Create Date: 2025-10-17 14:49:45.306113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a7075b8d11'
down_revision: Union[str, Sequence[str], None] = '3156dcf00f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('pickup_temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'pickup_temperature')
    # ### end Alembic commands ###
