# .github/workflows/main.yml
name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v2

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Build and push image'
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/bluemarina-mvp:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/bluemarina-mvp:${{ github.sha }}

      - name: 'Deploy to Azure Container Apps'
        uses: azure/container-apps-deploy@v1
        with:
          containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/bluemarina-mvp:${{ github.sha }}
          environmentVariables: 'DATABASE_URL=${{ secrets.DATABASE_URL }} SECRET_KEY=${{ secrets.SECRET_KEY }}'